services:
  nginxnp:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    env_file:
     - '/volume1/docker/.env'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - './data:/data'
      - './letsencrypt:/etc/letsencrypt'
    restart: unless-stopped