version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    env_file:
      - '/volume1/docker/.env'
    ports:
      - '8000:8000'
      - '9443:9443'
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    restart: unless-stopped
